name = "HyperSTARS"
uuid = "e47af67c-6139-4cdc-8d9c-9abfac86235b"
authors = ["Maggie Johnson <maggie.johnson@jpl.nasa.gov>", "Gregory Halverson <gregory.h.halverson@jpl.nasa.gov>", "Nimrod Carmon <nimrod.carmon@jpl.nasa.gov>", "Jouni Susiluoto <jouni.i.susiluoto@jpl.nasa.gov>"]
version = "1.2.0"

[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
BlockDiagonals = "0a1fb500-61f7-11e9-3c65-f5ef3456f9f0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GaussianRandomFields = "e4b2fa32-6e09-5554-b718-106ed5adafe9"
GeoArrays = "2fb1d81b-e6a0-5fc5-82e6-8e06903437ab"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KernelFunctions = "ec8451be-7e33-11e9-00cf-bbf324bd1392"
Kronecker = "2c470bb0-bcc8-11e8-3dad-c9649493f05e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Rasters = "a3a2b9e3-a471-40c9-b274-f788e487c689"
Sobol = "ed01d8cd-4d21-5b2a-85b4-cc3bdc58bad4"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
ArchGDAL = "0.10.8"
BlockDiagonals = "0.2.0"
Dates = "1.11.0"
Distances = "0.10.12"
Distributed = "1.11.0"
Distributions = "0.25.120"
GaussianRandomFields = "2.2.6"
GeoArrays = "0.9.4"
Interpolations = "0.16.1"
JLD2 = "0.5.15"
KernelFunctions = "0.10.65"
Kronecker = "0.5.5"
LinearAlgebra = "1.11.0"
MultivariateStats = "0.10.3"
Plots = "1.41.3"
ProgressMeter = "1.10.4"
Random = "1.11.0"
Rasters = "0.14.4"
Sobol = "1.5.0"
SparseArrays = "1.11.0"
Statistics = "1.11.1"
StatsBase = "0.34.5"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
